// Generated by tools/ui_art.py. Do not edit.
#pragma once
enum {
	UI_PLAY_18,
	UI_CHIP_18,
	UI_MEMCARD_18,
	UI_DVD_18,
	UI_CD_18,
	UI_HDD_18,
	UI_USB_18,
	UI_NET_18,
	UI_MX4SIO_18,
	UI_MMCE_18,
	UI_ILINK_18,
	UI_GEAR_18,
	UI_CAROUSEL_18,
	UI_GRID_18,
	UI_LIST_18,
	UI_MEMCARD_36,
	UI_MEMCARD_48,
	UI_CROSS_14,
	UI_CIRCLE_14,
	UI_TRIANGLE_14,
	UI_SQUARE_14,
	UI_SPARKLE_24,
	UI_SPARKLE_12,
	UI_DISC_6,
	UI_DISC_12,
	UI_DISC_14,
	UI_DISC_24,
	UI_DISC_26,
	UI_DISC_28,
	UI_DISC_30,
	UI_DISC_36,
	UI_DISC_38,
	UI_DISC_42,
	UI_DISC_44,
	UI_DISC_64,
	UI_COUNT
};
#define UI_ATLAS_W 256
#define UI_ATLAS_H 256
#define UI_GLOW 64
extern const unsigned char ui_atlas[], ui_glow[];
extern const unsigned short ui_rect[UI_COUNT][4]; // u, v, w, h
#define UI_ORB56 56
extern const unsigned char ui_orb56[];
extern const unsigned ui_orb56_clut[256];
#define UI_ORB110 110
extern const unsigned char ui_orb110[];
extern const unsigned ui_orb110_clut[256];
