// Generated by tools/ui_art.py. Do not edit.
#pragma once
enum {
	UI_PLAY_18,
	UI_CHIP_18,
	UI_MEMCARD_18,
	UI_DVD_18,
	UI_CD_18,
	UI_HDD_18,
	UI_USB_18,
	UI_NET_18,
	UI_MX4SIO_18,
	UI_MMCE_18,
	UI_ILINK_18,
	UI_MEMCARD_36,
	UI_MEMCARD_48,
	UI_CROSS_14,
	UI_CIRCLE_14,
	UI_TRIANGLE_14,
	UI_SQUARE_14,
	UI_SPARKLE_24,
	UI_SPARKLE_12,
	UI_DISC_64,
	UI_GLOW_64,
	UI_COUNT
};
#define UI_ATLAS_W 256
#define UI_ATLAS_H 128
#define UI_ORB 96
extern const unsigned char ui_atlas[], ui_orb[];
extern const unsigned ui_orb_clut[256];
extern const unsigned short ui_rect[UI_COUNT][4]; // u, v, w, h
