#!/usr/bin/env python3
"""Bake Inter (tools/fonts, OFL) into font_data.c: one 512-wide PSMT4 alpha atlas + glyph tables, two sizes.

usage: font.py [OUT.c]  (default: font_data.c next to the Makefile)  |  font.py --selftest
PSMT4 host layout: even-x pixel in the low nibble (docs/sources.md). CLUT index i = alpha i*128/15 (gfx.c).
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
TTF = ROOT / "tools" / "fonts" / "Inter.ttf"
SIZES = (("title", 36, 700), ("body", 22, 500))  # name, px, weight (design: phase-3-ui)
AW, PAGE_H, MAX_PAGES = 512, 128, 8              # PSMT4 page 128x128 -> 4 pages per 128 rows at 512 wide
PAD = 2  # blank texels between glyphs (a line above the glyphs showed on the console with 1)


def render(px, weight):
    f = ImageFont.truetype(str(TTF), px)
    f.set_variation_by_axes([min(32, max(14, px)), weight])  # axes: opsz 14-32, wght 100-900
    asc, desc = f.getmetrics()
    glyphs = []
    for c in range(32, 127):
        x0, y0, x1, y1 = f.getbbox(chr(c))
        im = Image.new("L", (max(1, x1 - x0), max(1, y1 - y0)))
        ImageDraw.Draw(im).text((-x0, -y0), chr(c), font=f, fill=255)
        glyphs.append(dict(img=im if x1 > x0 and im.getbbox() else None,  # blank (space): advance only
                            xo=x0, yo=y0, adv=round(f.getlength(chr(c)))))
    return glyphs, asc + desc


def pack(rects):  # rects: list of (w, h); returns [(x, y)] shelf-packed, PAD px apart, and used height
    order = sorted(range(len(rects)), key=lambda i: -rects[i][1])
    pos, x, y, shelf = [None] * len(rects), 0, 0, 0
    for i in order:
        w, h = rects[i]
        if x + w + PAD > AW:
            x, y, shelf = 0, y + shelf + PAD, 0
        pos[i] = (x, y)
        x, shelf = x + w + PAD, max(shelf, h)
    return pos, y + shelf


def build():
    fonts = [(name, *render(px, w)) for name, px, w in SIZES]
    items = [g for _, gl, _ in fonts for g in gl if g["img"]]
    pos, used = pack([g["img"].size for g in items])
    h = (used + PAGE_H - 1) // PAGE_H * PAGE_H
    assert AW // 128 * h // PAGE_H <= MAX_PAGES, f"atlas {AW}x{h} > {MAX_PAGES} pages"
    atlas = Image.new("L", (AW, h))
    for g, p in zip(items, pos):
        atlas.paste(g["img"], p)
        g["u"], g["v"] = p
    return fonts, atlas, items, pos


def c_source(fonts, atlas):
    a = [round(v * 15 / 255) for v in atlas.tobytes()]
    nib = bytes(a[i] | a[i + 1] << 4 for i in range(0, len(a), 2))
    out = ["// Generated by tools/font.py from Inter (SIL OFL 1.1, tools/fonts/OFL.txt). Do not edit.",
           '#include "gfx.h"',
           f"const int font_atlas_h = {atlas.height};",
           f"const unsigned char font_atlas[{len(nib)}] __attribute__((aligned(64))) = {{"]
    out += ["\t" + ",".join(str(b) for b in nib[i:i + 32]) + "," for i in range(0, len(nib), 32)]
    out.append("};")
    for name, gl, line_h in fonts:
        out.append(f"static const gfx_glyph {name}_glyphs[95] = {{")
        for g in gl:
            w, h = g["img"].size if g["img"] else (0, 0)
            out.append(f"\t{{{g.get('u', 0)}, {g.get('v', 0)}, {w}, {h}, {g['xo']}, {g['yo']}, {g['adv']}}},")
        out.append("};")
        out.append(f"const gfx_font gfx_font_{name} = {{ {name}_glyphs, {line_h} }};")
    return "\n".join(out) + "\n"


def selftest():
    fonts, atlas, items, pos = build()
    r = [(x, y, *g["img"].size) for g, (x, y) in zip(items, pos)]
    for i, (x, y, w, h) in enumerate(r):
        assert x + w <= AW and y + h <= atlas.height
        for x2, y2, w2, h2 in r[i + 1:]:
            assert x + w <= x2 or x2 + w2 <= x or y + h <= y2 or y2 + h2 <= y, "overlap"
    print(f"font selftest ok: {len(items)} glyphs, atlas {AW}x{atlas.height} = {AW // 128 * atlas.height // PAGE_H} pages")


if __name__ == "__main__":
    if sys.argv[1:] == ["--selftest"]:
        selftest()
    else:
        fonts, atlas, _, _ = build()
        out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "font_data.c"
        out.write_text(c_source(fonts, atlas), encoding="utf-8", newline="\n")
        print(f"{out}: atlas {AW}x{atlas.height}")
